project:
  type: website

website:
  title: "GISProject"
  navbar:
    left:
      - href: proposal.qmd
        text: Proposal
      - href: methodology.qmd
        text: Methodology
      - href: analysis.qmd
        text: Analysis & Findings
      - href: lessons.qmd
        text: Lessons Learned
      - href: poster.qmd
        text: Project Poster
      - href: minutes.qmd
        text: Meeting Minutes
    right:
      - href: index.qmd
        text: Home
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

