project:
  type: website

website:
  title: "GISProject"
  navbar:
    left:
      - href: introduction.qmd
        text: Introduction
      - href: proposal.qmd
        text: Proposal
      - href: methodology.qmd
        text: Methodology
      - href: analysis.qmd
        text: Analysis
      - href: findings.qmd
        text: Findings
      - href: lessons.qmd
        text: Lessons Learned
      - href: poster.qmd
        text: Project Poster
    right:
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

